name: gridorrhoea
favicon: null
layout_spectrum: 1
typography_spectrum: 0.40944
title: Gridorrhoea
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fbfdfd'
    - '#768ea0'
    - '#3e5b75'
    - '#d6a013'
  brandStrength: 1
  lightness: 0.75
  saturation: 0.875
  rhythmicContrast: 0.9811751318629831
purpose: []
