name: gridorrhoea
favicon: null
layout_spectrum: 1
typography_spectrum: 0.9731262887362391
title: Gridorrhoea
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fbfdfd'
    - '#768ea0'
    - '#3e5b75'
    - '#d6a013'
  brandStrength: 0.8623289559036493
  lightness: 0.4437095867469907
  saturation: 0.8804243188351393
  rhythmicContrast: 0.9811751318629831
purpose: []
